version: '3.11'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      FLASK_APP: uwsgi.py
      FLASK_ENV: production
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_DEBUG: False
      SQL_HOSTNAME: mysql
      SQL_USERNAME: remote_user
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB_NAME: ${SQL_DB_NAME}
      CELERY_BROKER_URL: "pyamqp://admin:${CELERY_BROKER_PASSWORD}@rabbitmq/vhost"
      CRYPT_KEY: ${CRYPT_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./app:/newutil/app
      - ./app/static:/newutil/app/static
      - ./config.py:/newutil/config.py
      - ./uwsgi.py:/newutil/uwsgi.py
      - user_files_volume:/newutil/app/user_files/
    networks:
      - appnet


  nginx:
    image: nginx:mainline-alpine
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - appnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email gavin@rawcsav.com --agree-tos --no-eff-email --staging -d newutil.rawcsav.com -d www.newutil.rawcsav.com

volumes:
  db_volume:
  rabbitmq_volume:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/rawcsav/AIUtilsFlask/web-root/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/rawcsav/AIUtilsFlask/dhparam/
      o: bind
  user_files_volume:  # New volume for user files

networks:
    appnet:
        driver: "bridge"
