version: '3.11'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      FLASK_APP: uwsgi.py
      FLASK_ENV: production
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_DEBUG: False
      SQL_HOSTNAME: mysql
      SQL_USERNAME: remote_user
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB_NAME: ${SQL_DB_NAME}
      CELERY_BROKER_URL: "pyamqp://admin:${CELERY_BROKER_PASSWORD}@rabbitmq/vhost"
      CRYPT_KEY: ${CRYPT_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./app:/newutil/app
      - ./app/static:/newutil/app/static
      - ./config.py:/newutil/config.py
      - ./uwsgi.py:/newutil/uwsgi.py
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - appnet


  nginx:
    image: nginx:mainline-alpine
    volumes:
      - web-root:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./app:/newutil/app
      - ./app/static:/newutil/app/static
      - dhparam:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - appnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email gavin@rawcsav.com --agree-tos --no-eff-email --force-renewal -d newutil.rawcsav.com -d www.newutil.rawcsav.com


  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DB_NAME}
      MYSQL_USER: remote_user
      MYSQL_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  rabbitmq:
    image: "rabbitmq:3"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${CELERY_BROKER_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: "vhost"
      CELERY_BROKER_URL: "pyamqp://admin:${CELERY_BROKER_PASSWORD}@rabbitmq/vhost"
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    networks:
      - appnet


  celery:
    build: .
    command: celery -A uwsgi.celery worker
    environment:
      FLASK_APP: uwsgi.py
      FLASK_ENV: production
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_DEBUG: False
      SQL_HOSTNAME: mysql
      SQL_USERNAME: remote_user
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB_NAME: ${SQL_DB_NAME}
      CELERY_BROKER_URL: "pyamqp://admin:${CELERY_BROKER_PASSWORD}@rabbitmq/vhost"
      CRYPT_KEY: ${CRYPT_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./app:/newutil/app
      - ./app/static:/newutil/app/static
      - ./config.py:/newutil/config.py
      - ./uwsgi.py:/newutil/uwsgi.py
    depends_on:
      - web
      - rabbitmq
    networks:
      - appnet

volumes:
  db_volume:
  rabbitmq_volume:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/rawcsav/AIUtilsFlask/web-root/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/rawcsav/AIUtilsFlask/dhparam/
      o: bind

networks:
    appnet:
        driver: "bridge"
