version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DB_NAME}
      MYSQL_USER: remote_user
      MYSQL_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - appnet

  rabbitmq:
    image: "rabbitmq:3"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${CELERY_BROKER_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: "vhost"
      CELERY_BROKER_URL: "pyamqp://admin:${CELERY_BROKER_PASSWORD}@rabbitmq/vhost"
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    depends_on:
      - mysql
    networks:
      - appnet

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      FLASK_APP: uwsgi.py
      FLASK_ENV: production
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_DEBUG: False
      SQL_HOSTNAME: mysql
      SQL_USERNAME: remote_user
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB_NAME: ${SQL_DB_NAME}
      CELERY_BROKER_URL: "pyamqp://admin:${CELERY_BROKER_PASSWORD}@rabbitmq/vhost"
      CRYPT_KEY: ${CRYPT_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./app:/newutil/app
      - ./app/static:/newutil/app/static
      - ./config.py:/newutil/config.py
      - ./uwsgi.py:/newutil/uwsgi.py
      - user_files_volume:/newutil/app/user_files/
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - appnet
    ports:
      - "8080:8080"

  celery:
    build: .
    command: celery -A uwsgi.celery worker --loglevel=info --concurrency=2 --pool=eventlet
    environment:
      FLASK_APP: uwsgi.py
      FLASK_ENV: production
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_DEBUG: False
      SQL_HOSTNAME: mysql
      SQL_USERNAME: remote_user
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB_NAME: ${SQL_DB_NAME}
      CELERY_BROKER_URL: "pyamqp://admin:${CELERY_BROKER_PASSWORD}@rabbitmq/vhost"
      CRYPT_KEY: ${CRYPT_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./app:/newutil/app
      - ./app/static:/newutil/app/static
      - ./config.py:/newutil/config.py
      - ./uwsgi.py:/newutil/uwsgi.py
      - user_files_volume:/newutil/app/user_files/
    depends_on:
      - web
      - rabbitmq
      - mysql
    networks:
      - appnet

volumes:
  db_volume:
  rabbitmq_volume:
  user_files_volume:  # New volume for user files

networks:
    appnet:
      external: true
