version: '3.11'

services:
  web:
    build: .
    environment:
      FLASK_APP: uwsgi.py
      FLASK_ENV: production
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_DEBUG: False
      SQL_HOSTNAME: mysql
      SQL_USERNAME: remote_user
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB_NAME: ${SQL_DB_NAME}
      CELERY_BROKER_URL: "pyamqp://admin:${CELERY_BROKER_PASSWORD}@rabbitmq/vhost"
      CRYPT_KEY: ${CRYPT_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./app:/newutil/app
      - ./conf:/newutil/conf
      - ./app/static:/newutil/app/static
      - ./config.py:/newutil/config.py
      - ./uwsgi.py:/newutil/uwsgi.py
    depends_on:
      - mysql
      - rabbitmq




  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DB_NAME}
      MYSQL_USER: remote_user
      MYSQL_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  rabbitmq:
    image: "rabbitmq:3"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${CELERY_BROKER_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: "vhost"
      CELERY_BROKER_URL: "pyamqp://admin:${CELERY_BROKER_PASSWORD}@rabbitmq/vhost"
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq

  nginx:
    image: nginx:latest
    volumes:
      - ./app:/newutil/app
      - ./conf:/newutil/conf
      - ./app/static:/newutil/app/static
      - ./config.py:/newutil/config.py
      - ./uwsgi.py:/newutil/uwsgi.py
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/sites-available:/etc/nginx/sites-available
      - ./conf/nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
          - "80:80"
    command: /bin/sh -c "rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - web

  celery:
    build: .
    command: celery -A uwsgi.celery worker
    environment:
      FLASK_APP: uwsgi.py
      FLASK_ENV: production
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_DEBUG: False
      SQL_HOSTNAME: mysql
      SQL_USERNAME: remote_user
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB_NAME: ${SQL_DB_NAME}
      CELERY_BROKER_URL: "pyamqp://admin:${CELERY_BROKER_PASSWORD}@rabbitmq/vhost"
      CRYPT_KEY: ${CRYPT_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./app:/newutil/app
      - ./conf:/newutil/conf
      - ./app/static:/newutil/app/static
      - ./config.py:/newutil/config.py
      - ./uwsgi.py:/newutil/uwsgi.py
    depends_on:
      - web
      - rabbitmq
volumes:
  db_volume:
  rabbitmq_volume:
