name: Deploy Docker Images

on:
  push:
    branches:
      - main  # Adjust if your primary branch has a different name
    paths:
      - '**.py'
      - 'Dockerfile'
      - 'requirements.txt'
      - '**.sh'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Web Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: yourusername/yourflaskapp:${{ github.sha }}

      - name: Build and Push Celery Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: yourusername/yourflaskapp-celery:${{ github.sha }}
